const data = {
    mob: {
        1: "Rock",
        2: "Cactus",
        3: "Ladybug",
        4: "Bee",
        5: "Baby Ant",
        6: "Worker Ant",
        7: "Soldier Ant",
        8: "Queen Ant",
        9: "Ant Hole",
        10: "Beetle",
        11: "Hornet",
        12: "Centipede",
        13: "Centipede [Body]",
        14: "Evil Centipede",
        15: "Evil Centipede [Body]",
        16: "Desert Centipede",
        17: "Desert Centipede [Body]",
        18: "Square",
        19: "Dark Ladybug",
        20: "Shiny Ladybug",
        21: "Spider",
        22: "Scorpion",
        23: "Soldier Fire Ant",
        24: "Fire Ant Burrow",
        25: "Sandstorm",
        26: "Bubble",
        27: "Bumble Bee",
        28: "Shell",
        29: "Starfish",
        30: "Crab",
        31: "Jellyfish",
        32: "Digger",
        33: "Sponge",
        34: "Leech",
        35: "Leech [Body]",
        36: "Dandelion",
        37: "Baby Fire Ant",
        38: "Worker Fire Ant",
        39: "Queen Fire Ant",
        40: "Ant Egg",
        41: "Fire Ant Egg",
        42: "Fly",
        43: "Leafbug",
        44: "Mantis",
        45: "Baby Termite",
        46: "Worker Termite",
        47: "Soldier Termite",
        48: "Termite Overmind",
        49: "Termite Mound",
        50: "Termite Egg",
        51: "Bush",
        52: "Roach",
        53: "Moth",
        54: "Firefly",
        55: "Hel Beetle",
        56: "Wasp",
        57: "Target Dummy",
        58: "Hel Spider",
        59: "Hel Centipede",
        60: "Hel Centipede [Body]",
        61: "Hel Wasp",
        62: "Trader",
        63: "Gambler",
        65: "Magic Firefly",
        66: "Titan"
    },
    petal: {
        1: "Basic",
        2: "Light",
        3: "Rock",
        4: "Square",
        5: "Rose",
        6: "Stinger",
        7: "Iris",
        8: "Wing",
        9: "Missile",
        10: "Grapes",
        11: "Cactus",
        12: "Faster",
        13: "Bubble",
        14: "Pollen",
        15: "Dandelion",
        16: "Beetle Egg",
        17: "Antennae",
        18: "Heavy",
        19: "Yin Yang",
        20: "Web",
        21: "Honey",
        22: "Leaf",
        23: "Salt",
        24: "Rice",
        25: "Corn",
        26: "Sand",
        27: "Pincer",
        28: "Yucca",
        29: "Magnet",
        30: "Yggdrasil",
        31: "Starfish",
        32: "Pearl",
        33: "Lightning",
        34: "Jelly",
        35: "Claw",
        36: "Shell",
        37: "Cutter",
        38: "Dahlia",
        39: "Uranium",
        40: "Sponge",
        41: "Soil",
        42: "Fangs",
        43: "Third Eye",
        44: "Peas",
        45: "Mysterious Stick",
        46: "Clover",
        47: "Mysterious Powder",
        48: "Air",
        49: "Basil",
        50: "Orange",
        51: "Ant Egg",
        52: "Poo",
        53: "Mysterious Relic",
        54: "Lotus",
        55: "Light Bulb",
        56: "Cotton",
        57: "Carrot",
        58: "Bone",
        59: "Plank",
        60: "Tomato",
        61: "Dark Mark",
        62: "Rubber",
        63: "Blood Stinger",
        64: "Bur",
        65: "Root",
        66: "Ankh",
        67: "Dice",
        68: "Talisman",
        69: "Battery",
        70: "Amulet",
        71: "Compass",
        72: "Disc",
        73: "Shovel",
        74: "Coin",
        75: "Poker Chip",
        76: "Card",
        77: "Moon Rock",
        78: "Privet Berry",
        79: "Glass",
        80: "Corruption",
        81: "Mana Orb",
        82: "Blueberries",
        83: "Magic Cotton",
        84: "Magic Stinger",
        85: "Magic Leaf",
        86: "Magic Cactus",
        87: "Magic Eye",
        88: "Magic Missile",
        89: "Magic Stick",
        90: "Coral",
        91: "Magic Bubble"
    }
}
